### ISSUE TITLE
Nice work!

### ISSUE THREAD

**Issue by ChoKaPeek** [sikvelsigma/ANSYS-WB-Batch-Script#1]
Hi, I really like this repo! This is really close to my use case and you have greatly inspired me. I have some questions if you don't mind.

I am very interested in how / where you found the documentation on the workbench API from WBInterface. Is it available somewhere? My company has a license, but so far I did not manage to get any way to contact the ANSYS support from them.

Is this considered as breaking ANSYS terms of use?

**Comment by ChoKaPeek** [comment]
@sikvelsigma

**Comment by sikvelsigma** [comment]
@ChoKaPeek The general Workbench Python API can be found in Workbench Scripting Guide online. The Mechanical js API can be accessed by exploring "...\aisol\DesignSpace" folder in ansys installation path. Generally, to find out how to do smth in Mechanical I will find the appropriate button for it, look at the caption, search that caption in all files in an aforementioned subfolder of ansys. After that you can find an ID associated with that caption, search that ID and find what methods are bound to it. Search the method itself as the last step. This article in 5 parts helped me with that (although some information about files is outdated since the release of the new ribbon interface): https://www.padtinc.com/blog/ansys-mechanical-scripting-howto-part-1/

I don't think it breaks any terms of service since ansys supports API execution natively both in Workbench and Mechanical (there's even a button called "Run Macro", would be pretty idiotic to have it and forbid using it), I didn't use any 3rd party software except for hooking up a debugger to Mechanical so I can see in real time js code execution and explore namespaces of objects, but that's just for development, it's not required to run it. As far as I'm aware there's no documentation on Mechanical js API but there's a separate Python API for Mechanical which is just a wrapper for js methods.

As a whole, my collection of scripts is just a wrapper of already existing API functionality and doesn't require any modification to ansys itself whatsoever.

If you have any ideas about what functionality you'd like to see, post them somewhere here. Generally, I add something new only if I need it in use in a project I'm working on right now, that's why there haven't been a lot of updates lately.

**Comment by sikvelsigma** [comment]
@ChoKaPeek also you can record Workbench python commands by using File -> Scripting -> Record Journal
Those journals are just python files
