### ISSUE TITLE
Ansys-WB-Batch-Script in Linux

### ISSUE THREAD

**Issue by altranapina** [sikvelsigma/ANSYS-WB-Batch-Script#2]
Hi, @sikvelsigma, firstly good work because your python script is perfect.

I have a question regarding the system where this script can be used. Is it possible to launch this script in Linux? I understand this script is only for Windows. But it could be adapted to Linux changing the run.bat archive?

Thanks in advance.

Regards,
altranapina

**Comment by sikvelsigma** [comment]
@altranapina i'm not sure what needs to be done to run it on Linux, the main concern is the use of .NET libraries for several key functions (since ironpython is natively a .NET language). As far as i'm aware, .net can run on Linux but i don't know if there's a difference between versions of ansys for windows and linux. As i don't have a linux system to test this (or a need to do so) i won't know until someone informs me if it's working or not.
